In [1]:
import tensorflow as tf
import numpy as np

In [2]:
some_list=[1,3,2,4]
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [3]:
some_list1=[1,5,3,2]
tf.one_hot(some_list1,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]], dtype=float32)>

In [4]:
tf.one_hot(some_list,depth=4,on_value='hello',off_value='bye')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'bye', b'hello', b'bye', b'bye'],
       [b'bye', b'bye', b'bye', b'hello'],
       [b'bye', b'bye', b'hello', b'bye'],
       [b'bye', b'bye', b'bye', b'bye']], dtype=object)>

In [5]:
#tf.square, tf.sqrt,tf.math.log

In [6]:
#tf.reduce_max(),tf.reduce_prod(),tf.argmax(),tf.argmin()

In [7]:
G=tf.constant(np.random.randint(0,100,50),shape=(1,1,1,1,50))
G.shape,G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [8]:
G_squeeze=tf.squeeze(G)
G_squeeze.shape,G_squeeze.ndim

(TensorShape([50]), 1)

In [9]:
B=tf.constant([1.7,7.4])
C=tf.cast(B,dtype=tf.float16)
B,C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>)

.assign() - assign a different value to a particular index of a variable tensor.
.add_assign() - add to an existing value and reassign it at a particular index of a variable tensor.

In [10]:
I=tf.Variable(np.arange(0,5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [11]:
I.assign([0,1,2,3,50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([ 0,  1,  2,  3, 50])>

In [12]:
I.assign_add([10,10,10,20,20])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([10, 11, 12, 23, 70])>

np.array() - pass a tensor to convert to a ndarray (NumPy's main datatype).
tensor.numpy() - call on a tensor to convert to a ndarray.

In [13]:
J=tf.constant(np.array([3.,7.,10.]))
J1=np.array(J)
J2=J.numpy()
J,J1,J2

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>,
 array([ 3.,  7., 10.]),
 array([ 3.,  7., 10.]))

In [14]:
@tf.function
def tf_function(x,y):
    return x**2+y
x=tf.constant(np.arange(0,10))
y=tf.constant(np.arange(10,20))
tf_function(x,y)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [15]:
gpus = tf.config.list_physical_devices('GPU')
print("GPUs available:", gpus)

GPUs available: []


In [16]:
!nvidia-smi

Thu May 16 10:49:12 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 536.19                 Driver Version: 536.19       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3070      WDDM  | 00000000:01:00.0  On |                  N/A |
| 30%   48C    P0              46W / 220W |   1979MiB /  8192MiB |     35%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant()

In [17]:
V1=tf.constant([10,5,4])
S1=tf.constant(10)
M1=tf.constant([[10,3,5],
                [2,6,4],
                [1,2,5]])
V1,S1,M1

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10,  5,  4])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=10>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[10,  3,  5],
        [ 2,  6,  4],
        [ 1,  2,  5]])>)

Find the shape, rank and size of the tensors you created in 1.

In [20]:
M1.ndim,tf.shape(M1),tf.rank(M1),tf.size(M1)

(2,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=9>)

Create two tensors containing random values between 0 and 1 with shape [5, 300]

In [21]:
R1=tf.random.uniform(shape=[5,300],minval=0,maxval=1)
R2=tf.random.uniform(shape=[5,300],minval=0,maxval=1)
R1,R2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.789644  , 0.17257857, 0.9165541 , ..., 0.0300858 , 0.36995125,
         0.7668561 ],
        [0.5834409 , 0.07012653, 0.22920871, ..., 0.97484124, 0.41976702,
         0.2790693 ],
        [0.38996935, 0.2905364 , 0.22521067, ..., 0.6166146 , 0.07772422,
         0.8844168 ],
        [0.03279972, 0.13195038, 0.6208793 , ..., 0.9997759 , 0.35373628,
         0.7085836 ],
        [0.96520674, 0.60565877, 0.48562992, ..., 0.67013   , 0.5366118 ,
         0.45016944]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.28474474, 0.96963763, 0.80763423, ..., 0.31817782, 0.6470914 ,
         0.6762922 ],
        [0.30655575, 0.6323496 , 0.72348857, ..., 0.48267913, 0.75658345,
         0.6541388 ],
        [0.8231605 , 0.10821152, 0.01528645, ..., 0.6403252 , 0.6189134 ,
         0.11296153],
        [0.76510775, 0.57062316, 0.7785436 , ..., 0.6758702 , 0.08756006,
         0.86888754],
        [0.64451

Multiply the two tensors you created in 3 using matrix multiplication.
Multiply the two tensors you created in 3 using dot product

In [29]:
MT1=tf.matmul(R1,tf.transpose(R2))

MT2=tf.tensordot(R1,tf.transpose(R2),axes=1)
MT1,MT2

(<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[72.96949 , 69.4985  , 75.03291 , 72.381836, 79.295235],
        [71.71681 , 68.75    , 76.61481 , 72.09191 , 79.99255 ],
        [64.81653 , 63.77592 , 68.261314, 66.161545, 73.200905],
        [71.85776 , 71.60929 , 76.89269 , 71.264206, 79.12492 ],
        [70.58033 , 69.79489 , 74.59768 , 69.628334, 78.64021 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[72.96949 , 69.4985  , 75.03291 , 72.381836, 79.295235],
        [71.71681 , 68.75    , 76.61481 , 72.09191 , 79.99255 ],
        [64.81653 , 63.77592 , 68.261314, 66.161545, 73.200905],
        [71.85776 , 71.60929 , 76.89269 , 71.264206, 79.12492 ],
        [70.58033 , 69.79489 , 74.59768 , 69.628334, 78.64021 ]],
       dtype=float32)>)

Create a tensor with random values between 0 and 1 with shape [224, 224, 3].


In [30]:
T1=tf.random.uniform(shape=[224,224,3],minval=0,maxval=1)
T1

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.5983143 , 0.03362739, 0.49445426],
        [0.5643481 , 0.10439372, 0.5118773 ],
        [0.00610089, 0.71662426, 0.1605227 ],
        ...,
        [0.82940733, 0.38050282, 0.05694962],
        [0.35988498, 0.5003172 , 0.9666573 ],
        [0.81760395, 0.5786804 , 0.20229709]],

       [[0.44126248, 0.9720149 , 0.27271557],
        [0.6782805 , 0.8630806 , 0.47211707],
        [0.47792017, 0.91811085, 0.43056452],
        ...,
        [0.34374118, 0.3128215 , 0.53161407],
        [0.41706073, 0.38692784, 0.25574684],
        [0.5513288 , 0.26505423, 0.17977047]],

       [[0.76519144, 0.8704493 , 0.994931  ],
        [0.9972819 , 0.10987401, 0.7344117 ],
        [0.9824033 , 0.0194701 , 0.6118089 ],
        ...,
        [0.3686651 , 0.9161235 , 0.61187243],
        [0.1665684 , 0.0294143 , 0.12802982],
        [0.7086643 , 0.5294471 , 0.9440514 ]],

       ...,

       [[0.44809198, 0.640074  , 0.05831015],
        [0.97

Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [32]:
T2=tf.random.uniform(shape=[1,224,224,3],minval=0,maxval=1)
T2_sq=tf.squeeze(T2)
T2.shape,T2_sq.shape

(TensorShape([1, 224, 224, 3]), TensorShape([224, 224, 3]))

Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [43]:
T3=tf.random.uniform(shape=[10],minval=0,maxval=10,dtype=tf.int32)
m3=tf.reduce_max(T3)
T3,m3

(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([7, 7, 7, 1, 9, 1, 9, 5, 2, 0])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=9>)

One-hot encode the tensor you created in 9.


In [44]:
o1=tf.one_hot(T3,depth=10)
o1

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>